### ISSUE TITLE
How to use info files?

### ISSUE THREAD

**Issue by bromagosa** [Rydion/SnapSubset#2]
I'm building a [Snap! command line interpreter](https://github.com/bromagosa/snap-interpreter) and it currently runs very slow in embedded systems, which is why I wanted to use SnapSubset to get rid of all the features I'm not using, as I estimate around 80% of the code is being loaded and never called.

Thing is, I can't seem to understand how `.info` files work. How does one determine which prototypes and functions should be removed from the result? Not including them in the `.info` file doesn't seem to do the trick.

**Comment by adrian-hintze** [comment]
Hi,
yeah my university email account seems to have been terminated permanently.
Doesn't GitHub provide any kind of messaging system? I could provide you with one of my personal email addresses if necessary.

As for .info files, if they are written correctly they should indeed get rid of all code that is NOT included in them. If it's not happening the issue must be laying somewhere else. Can you provide me with an example of an .info file that you are using and the corresponding input and output files? I'll take a look at them and try to figure out what's going on.
